all: q1 q12 q2 q33 
q1:q1.c uniform.c expon.c
	gcc q1.c uniform.c expon.c -lm -o q1
q12:q12.c uniform.c expon.c
	gcc q12.c uniform.c expon.c -lm -o q12
q2:q2.c uniform.c expon.c
	gcc q2.c uniform.c expon.c -lm -o q2
q33:q33.c uniform.c expon.c
	gcc q33.c uniform.c expon.c -lm -o q33

clean:
	rm q1 q12 q2 q33
