all: q1 q21 q22 q23 q24 q3
q1:
	gcc q1.c uniform.c expon.c -lm -o q1
q21:
	gcc q21.c uniform.c expon.c -lm -o q21
q22:
	gcc q22.c uniform.c expon.c -lm -o q22
q23:
	gcc q23.c uniform.c expon.c -lm -o q23
q24:
	gcc q24.c uniform.c expon.c -lm -o q24
q3:
	gcc q3.c uniform.c expon.c -lm -o q3
clean:
	rm q1 q21 q22 q23 q24 q3
